// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD5t6XO62fxyKeuIiyg6rLhJoGScpJStk',
    appId: '1:736072853872:web:a9de8c5878541b1c6a87b5',
    messagingSenderId: '736072853872',
    projectId: 'spotify-16582',
    authDomain: 'spotify-16582.firebaseapp.com',
    storageBucket: 'spotify-16582.firebasestorage.app',
    measurementId: 'G-1Z740WRZYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYSk7D0nbQ6TRi2ptxHAunw9AnwSmza3s',
    appId: '1:736072853872:android:b5751620776cd44a6a87b5',
    messagingSenderId: '736072853872',
    projectId: 'spotify-16582',
    storageBucket: 'spotify-16582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA21qTkqlacN63VVa5ZfVRSGgWeYSOdtU',
    appId: '1:736072853872:ios:df86392028fd83716a87b5',
    messagingSenderId: '736072853872',
    projectId: 'spotify-16582',
    storageBucket: 'spotify-16582.firebasestorage.app',
    iosBundleId: 'com.spotifyclone.spotifyClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA21qTkqlacN63VVa5ZfVRSGgWeYSOdtU',
    appId: '1:736072853872:ios:df86392028fd83716a87b5',
    messagingSenderId: '736072853872',
    projectId: 'spotify-16582',
    storageBucket: 'spotify-16582.firebasestorage.app',
    iosBundleId: 'com.spotifyclone.spotifyClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD5t6XO62fxyKeuIiyg6rLhJoGScpJStk',
    appId: '1:736072853872:web:d522f94f5ec7557a6a87b5',
    messagingSenderId: '736072853872',
    projectId: 'spotify-16582',
    authDomain: 'spotify-16582.firebaseapp.com',
    storageBucket: 'spotify-16582.firebasestorage.app',
    measurementId: 'G-WQC21MBCWN',
  );
}
